select * from DARBUOTOJAI;

SELECT * FROM DARBUOTOJAI WHERE SKYRIUS_PAVADINIMAS = "Gamybos" OR PAREIGOS = "Vadybininkas" ORDER BY "Vardas" DESC;

SELECT
	count(*)
FROM
	DARBUOTOJAI
WHERE GIMIMO_DATA like "%1986%"

SELECT
	PAREIGOS,
	count(*)
FROM
	DARBUOTOJAI
GROUP BY
	PAREIGOS;
	
SELECT
	*
FROM
	DARBUOTOJAI
WHERE
	GIMIMO_DATA BETWEEN "1980-01-01" AND "1990-01-01"
	
INSERT INTO DARBUOTOJAI VALUES(
"Jotautas", "Treigys", "jtr@gmail.com", "Male", date('1981-04-25'));	

INSERT INTO DARBUOTOJAI 
	(VARDAS, PAVARDĖ, GIMIMO_DATA, SKYRIUS_PAVADINIMAS)
VALUES
	("Antanas", "Šampanas", date('1979-02-02'), "Gamybos");
	
UPDATE DARBUOTOJAI SET PAREIGOS = "Testuotojas" WHERE Vardas = "Antanas" AND PAVARDĖ = "Šampanas";

DELETE FROM DARBUOTOJAI where VARDAS = "Antanas";